### ISSUE TITLE
More laconic record

### ISSUE THREAD

**Issue by IanaKhitsko** [TGIfr/euro-diffusion#4]
https://github.com/TGIfr/euro-diffusion/blob/c0715386c686accf6aac28b3202d1824b8606ca3/Grid.cs#L61-L62

if ( var curCity = Cities[i, y])
{
   ...
}

**Comment by TGIfr** [comment]
It won't work
The closest possible form is 
City curCity ;
 if((curCity = Cities[i, y]) == null)

It`s less obvious in my opinion
