### ISSUE TITLE
Change typing to implicit

### ISSUE THREAD

**Issue by Miracle-Aligner** [TGIfr/euro-diffusion#6]
Use implicit typing for local variables when the type of the variable is obvious from the right side of the assignment, or when the precise type is not important.

i.e.:

https://github.com/TGIfr/euro-diffusion/blob/4dee3fc4a2fbc817b44be642766b22735f52ce56/Country.cs#L10
https://github.com/TGIfr/euro-diffusion/blob/4dee3fc4a2fbc817b44be642766b22735f52ce56/Country.cs#L12-L13

https://github.com/TGIfr/euro-diffusion/blob/4dee3fc4a2fbc817b44be642766b22735f52ce56/Grid.cs#L10-L11

**Comment by Miracle-Aligner** [comment]
Also, use implicit typing in loop variables assignment

https://github.com/TGIfr/euro-diffusion/blob/4dee3fc4a2fbc817b44be642766b22735f52ce56/Grid.cs#L47-L50

**Comment by TGIfr** [comment]
Implicit typing is impossible in C# for the first five cases
Fixed in loop
