### ISSUE TITLE
Change implicit typing where it isn't obvious

### ISSUE THREAD

**Issue by Miracle-Aligner** [TGIfr/euro-diffusion#7]
Do not use var when the type is not apparent from the right side of the assignment.

https://github.com/TGIfr/euro-diffusion/blob/4dee3fc4a2fbc817b44be642766b22735f52ce56/Grid.cs#L42-L45
https://github.com/TGIfr/euro-diffusion/blob/4dee3fc4a2fbc817b44be642766b22735f52ce56/Parser.cs#L16

**Comment by TGIfr** [comment]
Fixed
