### ISSUE TITLE
New Operator 

### ISSUE THREAD

**Issue by Miracle-Aligner** [TGIfr/euro-diffusion#9]
Use the concise form of object instantiation, with implicit typing
> public var Money = new Dictionary<int, int>();

https://github.com/TGIfr/euro-diffusion/blob/4dee3fc4a2fbc817b44be642766b22735f52ce56/City.cs#L14-L17

**Comment by TGIfr** [comment]
This form is impossible in C#
Possible fix is this form from C# 9 which will come soon 
> public Dictionary<int, int> Money = new ();
